service: serverless-sample

provider:
  name: aws
  runtime: nodejs6.10
  stage: demo
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "apigateway:GET"
      Resource:
        - "arn:aws:apigateway:${self:provider.region}::/restapis*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-aws-documentation
  - serverless-domain-manager
  - serverless-stack-output

package:
  include:
    src/**/!(*.spec).js
  exclude:
    - node_modules/**/*

functions:
  registerUser:
    handler: src/auth/auth.register
    description: Register a new User.

    environment:

    events:
      - http:
          path: auth/register
          method: post
          cors: true
          documentation:
            summary: Register a new user.
            tags:
              - Auth
            description: Returns the new user.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  "application/json": RegisterOutputModel
              - ${file(./swagger/error-responses/bad-request.yml)}
              - ${file(./swagger/error-responses/forbidden.yml)}
              - ${file(./swagger/error-responses/not-found.yml)}
              - ${file(./swagger/error-responses/internal-server-error.yml)}
custom:
  documentation: ${file(./swagger/documentation.yml)}
  customDomain:
    basePath: "api"
    domainName: serverless-sample.balassy.me
    certificateName: serverless-sample.balassy.me
    stage: ${self:provider.stage}
    createRoute53Record: true
  output:
    file: .serverless/output.json
